### ISSUE TITLE
Chancel Atlassian JIRA and Confluence accounts

### ISSUE THREAD

**Issue by daddymccoy** [Betolio/Admin#3]
@daddymccoy commented on [Mon Apr 04 2016](https://github.com/Betolio/App/issues/16)

**Comment by johanssonchris** [comment]
I have informed the Atlassian team to cancel our subscription, awaiting their reply.

**Comment by johanssonchris** [comment]
I am not sure if I can access the billing information. Do you have access to it?

**Comment by daddymccoy** [comment]
I have cancelled the account.
