### ISSUE TITLE
Upgrade Github account to private

### ISSUE THREAD

**Issue by daddymccoy** [Betolio/Admin#4]
@daddymccoy commented on [Mon Apr 04 2016](https://github.com/Betolio/App/issues/15)

**Comment by daddymccoy** [comment]
Can you get this this today @johanssonchris?

**Comment by johanssonchris** [comment]
Yes. Will do tonight

**Comment by daddymccoy** [comment]
Thanks.

**Comment by johanssonchris** [comment]
I entered credit card info, is it private now?

**Comment by johanssonchris** [comment]
never mind...it's now in private

**Comment by daddymccoy** [comment]
What is the monthly cost
